# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyLiked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_id', models.CharField(max_length=128)),
                ('time', models.DateTimeField(verbose_name='\u70b9\u8d5e\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='LikerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=128)),
                ('cookie', models.CharField(max_length=512)),
            ],
        ),
    ]
